name: Building Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    name: "Building Docker image"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout on the latest commit
        uses: actions/checkout@v3

      - name: Git tagging
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'noreply-bot@github.com'
          git tag -a "${{ github.event.inputs.version }}" -m "Release v${{ github.event.inputs.version }}" HEAD
          git push --tags

      - name: Checkout on the latest tag
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.version }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
